### PR TITLE
Add support for a full request timeout

### LINKED ISSUE #35: Inability to configure full request timeout leads to DoS / resource leak
attohttpc currently does not allow specifying a timeout for the entire request (i.e. until the request body is finished transferring), which means an established connection will hang indefinitely if the remote host doesn't stops replying. This leads to a resource leak, which may cause denial of service. This post explains the problem in detail: https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779

While it's not necessary to set such timeout by default (most other HTTP clients don't), it must be possible to configure it for attohttpc to be usable for e.g. building reliable services that query a remiote API over HTTP, or for defending against DoS attacks where the remote host sends 1 byte per second, keeping the connection open indefinitely.

### PR DESCRIPTION
**Pull request by adamreichold**
By racing another thread which shuts down the socket when the timeout is elapsed.

Closes #35

### CODE REVIEW

**Comment by sbstp** [comment]
Hey! Thanks for this. It's a clean way of doing it. Do you think that we could use like an AtomicBool or something like that to signal the BaseStream that the UnexpectedEOF was caused by the request timeout? Then we can return a timeout error instead of UnexpectedEOF.

**Comment by adamreichold** [comment]
> Then we can return a timeout error instead of UnexpectedEOF.

Yes, but we would have keep that flag around (`Arc<AtomicBool>` to ensure a sufficiently long lifetime, adding a field to `BaseStream`) and we would have to check it after every failed read.

Personally, I think the code complexity this adds is not worth the change to the more relevant error code (`io::ErrorKind` is already rather vague as it is, e.g. `WouldBlock` and `TimedOut` depending on platform), especially since simplicity is the whole point of this approach.

**Comment by adamreichold** [comment]
> we would have to check it after every failed read.

Actually worse, we have to check every read as this yields a "clean" read of length zero.

**Comment by sbstp** [comment]
I don't really mind carrying an Arc<AtomicBool> around. I think we could map on the error returned by `parse_response` and add a method to the BaseStream to check if the thread timedout.

```rust
let mut stream = BaseStream::connect(&info)?;
self.write_request(&mut stream, &url)?;
let resp = match parse_response(stream, self).map_err(|err| {
    if let ErrorKind::Io(io_err) = err.kind() {
        if let io::ErrorKind::UnexpectedEof = io_err.kind() {
            if stream.timeout_reached() {
                return ErrorKind::Timeout;
            }
        }
    }
    err
});
```

We could also use a channel and recv_timeout to end the thread sooner if the request finishes quickly. On drop BaseStream could send something to wake up the timeout thread and tell it to end.

**Comment by sbstp** [comment]
You don't actually need to send anything in the channel. On drop it will get disconnected.
```rust
match rx.recv_timeout(timeout) {
  Err(RecvTimeoutError::Timeout) => stream.shutdown(Shutdown::Both),
  _ => { // end thread }
}
```

**Comment by sbstp** [comment]
Forget what I said it doesn't make sense. You can still read the body after the parse_response call, you could timeout while reading the body.

**Comment by adamreichold** [comment]
> We could also use a channel and recv_timeout to end the thread sooner if the request finishes quickly. 

I have implemented this and pushed it as separate commit. It is you prerogative to make this choice, but personally I still think the complexity cost is completely unproportional for such a fringe feature.

**Comment by sbstp** [comment]
Let's take some time to think about it. Even if we decide to remove the error check in the BaseStream, I think we should keep the channel to terminate the thread early when the Response is dropped quickly. If for some reason someone puts a really large timeout, we start leaking threads.

**Comment by adamreichold** [comment]
> If for some reason someone puts a really large timeout, we start leaking threads.

Using a single thread that just sleeps until the next deadline might be a more resource efficient solution but not we are talking about inventing a timer wheel...

**Comment by sbstp** [comment]
Looks like the pipeline failed. Race condition? Spurious? Genuine failure?

**Comment by adamreichold** [comment]
> Looks like the pipeline failed. Race condition? Spurious? Genuine failure?

Spurious but also genuine: I it necessary to explicitly drop the receiver as otherwise we can still receive another item after having called `shutdown` so that sending will not fail and we will not consider this a timeout. But then again, the failure mode is replacing one I/O error kind by another...

**Comment by sbstp** [comment]
I'm ok with removing the code that converts the error from UnextectedEof to a timeout, but I'd like to keep the channel that closes the thread as soon as the response is dropped.

**Comment by adamreichold** [comment]
> I'm ok with removing the code that converts the error from UnextectedEof to a timeout, but I'd like to keep the channel that closes the thread as soon as the response is dropped.

Done. (The changes in the redirection test are due to `cargo fmt`. Maybe we should include checking the formatting in the CI?)

**Comment by adamreichold** [comment]
Sorry for the CI noise, I messed up the test during rebase.

**Comment by sbstp** [comment]
Thanks! I'll release this & the redirect fix right away.

**Pull request merged**
