### PR TITLE
Try implementing timeouts on Windows by directly closing the underlying socket from the timeout thread.

### LINKED ISSUE #118: Timeout not working on Windows
I'm making a request with timeout set to `Duration::from_secs(2)` to a dummy localhost server. The server sleeps for `Duration::from_secs(5)` before responding, and the timeout is not enforced on Windows (though it works on macOS and Linux).

### PR DESCRIPTION
**Pull request by adamreichold**
Closes #118

### CODE REVIEW

**Comment by adamreichold** [comment]
The test fails due to the wrong error condition being returned, but I'd like to know if this helps at all before trying to figure that one out.

**Comment by lucasfernog** [comment]
Works like a charm @adamreichold

**Comment by adamreichold** [comment]
> Works like a charm @adamreichold

Glad to hear that. I will look into fixing the error code next. Might take a day or two though.

**Comment by adamreichold** [comment]
@sbstp I think this is ready for review now. The usage of unsafe is unfortunate, but I think unavoidable (as std does not call 'closesocket' itself) and mostly harmless (we just pass a socket handle, not raw pointers, into the unsafe function).

**Comment by sbstp** [comment]
I wonder if this would be worth reporting to upstream, looks like it might be an issue/oversight in `std`.

Changes looks OK.

**Comment by adamreichold** [comment]
> I wonder if this would be worth reporting to upstream, looks like it might be an issue/oversight in `std`.

I don't think so because std does not make any guarantees about the pattern we are using (closing/shutting down a socket blocked else to unblock that thread). It is just not part of their API contract and it working on Unix is a bit of coincidence.

**Pull request merged**
